### PR TITLE
Dependencies: Update

### PR DESCRIPTION
**Pull request by Jannis25**
Updated dependencies to the newest versions, except for `blis` and `numpy` due to `thinc` requiring `blis<0.8.0` and `numpy<2.0`.
Additionally added all missing dependencies to [pyproject.toml](https://github.com/DataManagementLab/wannadb/blob/bc23c9704908fc6e8d4f636a02c24dbdb06fba13/pyproject.toml).
Compatible python versions are all `>=3.10`.

### CODE REVIEW

**Comment by bhaettasch** [comment]
It looks like (at least on Windows) networkx==3.3 and scipy==1.14.0 are not available for Python 3.9, and matplotlib==3.9.1 has to be built from the sources, which might not be working on every machine. Could you please check whether this is a general issue with python 3.9?
In general, we could consider enforcing a newer version, since 3.9 will reach end of life in one year.

**Comment by Jannis25** [comment]
> It looks like (at least on Windows) networkx==3.3 and scipy==1.14.0 are not available for Python 3.9, and matplotlib==3.9.1 has to be built from the sources, which might not be working on every machine. Could you please check whether this is a general issue with python 3.9? In general, we could consider enforcing a newer version, since 3.9 will reach end of life in one year.

I updated the project, tool, and README to enforce a Python version of 3.10 or higher. Additionally, I updated Matplotlib to version 3.9.2, which has a pre-built binary wheel.

**Comment by bhaettasch** [comment]
After creating a new clean virtualenv with python 3.10 and installing all dependencies, I get the following error when running main.py:

[WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "D:\repo\wannadb\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by Jannis25** [comment]
Issue should be fixed by upgrading to `torch==2.4.1`.
Tested on Windows 11 on VM.

**Comment by bhaettasch** [comment]
Still caused an issue, but when using sentence-transformers[train] instead of just sentence-transformers in the requirements file, it works for me. Can you please adjust and verify?

**Pull request merged**
